<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.cmdbuild</groupId>
        <artifactId>cmdbuild-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../parent</relativePath>
    </parent>

    <groupId>org.cmdbuild</groupId>
    <artifactId>cmdbuild-ui</artifactId>
    <version>${revision}</version>
    <packaging>war</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.4.0</version>
                <executions>
                    <!-- Install npm dependencies -->
                    <execution>
                        <id>npm-install</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npm</executable>
                            <arguments>
                                <argument>install</argument>
                            </arguments>
                        </configuration>
                    </execution>

                    <!-- Run your app build (e.g., webpack, vite, rollup, etc.) -->
                    <execution>
                        <id>npm-build</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npm</executable>
                            <arguments>
                                <argument>run</argument>
                                <argument>build</argument>
                            </arguments>
                        </configuration>
                    </execution>

                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <packagingExcludes>WEB-INF/lib/*</packagingExcludes>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <webResources>
                        <resource>
                            <directory>build/testing/CMDBuildUI</directory>
                            <targetPath>ui_dev</targetPath>
                        </resource>
<!--                        <resource>-->
<!--                            <directory>build/production/CMDBuildUI</directory>-->
<!--                            <targetPath>ui</targetPath>-->
<!--                        </resource>-->
                    </webResources>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
